/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vivek_wo_jni_JniExample_OnJNICallback */

#ifndef _Included_com_vivek_wo_jni_JniExample_OnJNICallback
#define _Included_com_vivek_wo_jni_JniExample_OnJNICallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
