/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vivek_wo_jni_JniExample */

#ifndef _Included_com_vivek_wo_jni_JniExample
#define _Included_com_vivek_wo_jni_JniExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vivek_wo_jni_JniExample
 * Method:    onJniCall
 * Signature: (Ljava/lang/String;I[BLcom/vivek/wo/jni/JniExample/OnJNICallback;)V
 */
JNIEXPORT void JNICALL Java_com_vivek_wo_jni_JniExample_onJniCall
  (JNIEnv *, jobject, jstring, jint, jbyteArray, jobject);

/*
 * Class:     com_vivek_wo_jni_JniExample
 * Method:    onJniExecute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vivek_wo_jni_JniExample_onJniExecute
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
