/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vivek_wo_jni_JniExample */

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vivek_wo_jni_JniExample
 * Method:    onJniCall
 * Signature: (Ljava/lang/String;I[BLcom/vivek/wo/jni/JniExample/OnJNICallback;)V
 */
JNIEXPORT void JNICALL Java_com_vivek_wo_jni_JniExample_onJniCall
        (JNIEnv *env, jobject thiz, jstring jarg1, jint jarg2, jbyteArray jarg3,
         jobject jcallback){
}

/*
 * Class:     com_vivek_wo_jni_JniExample
 * Method:    onJniExecute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vivek_wo_jni_JniExample_onJniExecute
        (JNIEnv *env, jobject thiz) {

}

#ifdef __cplusplus
}
#endif
