/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
#include <android/log.h>
/* Header for class com_vivek_wo_jni_JniExample */

#ifdef __cplusplus
extern "C" {
#endif

#define TAG "_JNI_TAG_"
#define _jni_log_(...) __android_log_print(ANDROID_LOG_WARN, TAG, __VA_ARGS__);

/*
 * Class:     com_vivek_wo_jni_JniExample
 * Method:    onJniCall
 * Signature: (Ljava/lang/String;I[BLcom/vivek/wo/jni/JniExample$OnJNICallback;)V
 */
JNIEXPORT void JNICALL Java_com_vivek_wo_jni_JniExample_onJniCall
        (JNIEnv *env, jobject thiz, jstring jarg1, jint jarg2, jbyteArray jarg3,
         jobject jcallback) {
    const char *arg1 = env->GetStringUTFChars(jarg1, NULL);
    _jni_log_("onJniCall Method arg1: %s, arg2: %d", arg1, jarg2);
}

/*
 * Class:     com_vivek_wo_jni_JniExample
 * Method:    onJniExecute
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vivek_wo_jni_JniExample_onJniExecute
        (JNIEnv *env, jobject thiz) {
    _jni_log_("onJniExecute Method");
    const char arg1[] = "onJniExecute result?";
    jstring jarg1 = env->NewStringUTF(arg1);
//    env->DeleteLocalRef(jarg1);
    return jarg1;
}

static void
android_onJniDynamicCall(JNIEnv *env, jobject thiz, jstring jarg1, jint jarg2, jbyteArray jarg3,
                         jobject jcallback) {
    const char *arg1 = env->GetStringUTFChars(jarg1, NULL);
    _jni_log_("android_onJniDynamicCall Method arg1: %s, arg2: %d", arg1, jarg2);
    env->ReleaseStringUTFChars(jarg1, arg1);
}

static jint android_onJniDynamicExecute(JNIEnv *env, jobject thiz) {
    return 30;
}

static const JNINativeMethod gMethods[] = {
        {"onJniDynamicCall",//Java方法
                "(Ljava/lang/String;I[BLcom/vivek/wo/jni/JniExample$OnJNICallback;)V",//方法签名
                (void *) android_onJniDynamicCall},//Native方法
        {"onJniDynamicExecute",
                "()I",
                (void *) android_onJniDynamicExecute}
};

JNIEXPORT jint JNI_OnLoad(JavaVM *vm, void *reserved) {
    JNIEnv *env = NULL;
    jint result = -1;

    if (vm->GetEnv((void **) &env, JNI_VERSION_1_4) != JNI_OK) {
        return result;
    }

    jclass clazz = env->FindClass("com/vivek/wo/jni/JniExample");
    if (clazz == NULL) {
        return result;
    }

    if (env->RegisterNatives(clazz, gMethods, sizeof(gMethods) / sizeof(gMethods[0])) < 0) {
        return result;
    }

    result = JNI_VERSION_1_4;
    return result;

}


#ifdef __cplusplus
}
#endif
